# Pytorch

- __`torch`__: a Tensor library like NumPy, with strong GPU support
- __`torch.autograd`__: a tape based automatic differentiation library that supports all differentiable Tensor operations in torch
- __`torch.nn`__: a neural networks library deeply integrated with autograd designed for maximum flexibility
- __`torch.optim`__: an optimization package to be used with torch.nn with standard optimization methods such as SGD, RMSProp, LBFGS, Adam etc.
- __`torch.multiprocessing`__: python multiprocessing, but with magical memory sharing of torch Tensors across processes. Useful for data loading and hogwild training.
- __`torch.utils`__: DataLoader, Trainer and other utility functions for convenience
- __`torch.legacy`(.nn/.optim)__: legacy code that has been ported over from torch for backward compatibility reasons


In [1]:
import numpy as np
import torch

## Similarity of Numpy Array and Pytorch Tensor

### numpy

In [2]:
row_dim = 4
col_dim = 5

In [3]:
x = np.random.rand(row_dim, col_dim)

In [4]:
print(type(x))
print(f'Shape of x: {x.shape}\n')
x

<class 'numpy.ndarray'>
Shape of x: (4, 5)



array([[0.88460048, 0.96267488, 0.48854612, 0.56863165, 0.85378663],
       [0.97602425, 0.29354704, 0.28666635, 0.32662137, 0.652663  ],
       [0.58295181, 0.93856269, 0.89765355, 0.61254644, 0.71330168],
       [0.67603373, 0.90321333, 0.54460977, 0.9179991 , 0.93296974]])

In [5]:
ones_x = np.ones(x.shape)

ones_x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
res_x = x + ones_x

res_x

array([[1.88460048, 1.96267488, 1.48854612, 1.56863165, 1.85378663],
       [1.97602425, 1.29354704, 1.28666635, 1.32662137, 1.652663  ],
       [1.58295181, 1.93856269, 1.89765355, 1.61254644, 1.71330168],
       [1.67603373, 1.90321333, 1.54460977, 1.9179991 , 1.93296974]])

In [7]:
res_x[0]

array([1.88460048, 1.96267488, 1.48854612, 1.56863165, 1.85378663])

In [8]:
res_x[:, 2:4]

array([[1.48854612, 1.56863165],
       [1.28666635, 1.32662137],
       [1.89765355, 1.61254644],
       [1.54460977, 1.9179991 ]])

In [9]:
res_x[1:3, :]

array([[1.97602425, 1.29354704, 1.28666635, 1.32662137, 1.652663  ],
       [1.58295181, 1.93856269, 1.89765355, 1.61254644, 1.71330168]])

### pytorch

In [10]:
y = torch.rand(row_dim, col_dim)

In [11]:
print(type(y))
print(f'Shape of y: {y.shape}\n')
y

<class 'torch.Tensor'>
Shape of y: torch.Size([4, 5])



tensor([[0.3190, 0.7024, 0.7576, 0.4048, 0.8386],
        [0.3427, 0.7705, 0.4187, 0.7239, 0.3240],
        [0.1501, 0.5568, 0.8509, 0.4983, 0.4110],
        [0.2643, 0.4154, 0.3221, 0.3416, 0.2059]])

In [12]:
ones_y = torch.ones(y.shape)

ones_y

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
res_y = y + ones_y

res_y

tensor([[1.3190, 1.7024, 1.7576, 1.4048, 1.8386],
        [1.3427, 1.7705, 1.4187, 1.7239, 1.3240],
        [1.1501, 1.5568, 1.8509, 1.4983, 1.4110],
        [1.2643, 1.4154, 1.3221, 1.3416, 1.2059]])

In [14]:
res_y[0]

tensor([1.3190, 1.7024, 1.7576, 1.4048, 1.8386])

In [15]:
res_y[:, 2:4]

tensor([[1.7576, 1.4048],
        [1.4187, 1.7239],
        [1.8509, 1.4983],
        [1.3221, 1.3416]])

In [16]:
res_y[1:3, :]

tensor([[1.3427, 1.7705, 1.4187, 1.7239, 1.3240],
        [1.1501, 1.5568, 1.8509, 1.4983, 1.4110]])

## Special Functions

In Pytorch almost every operation over tensor may change the tensor inpalce or return a new tensor. 
- the function with under-score after its name change the tensor inplace
- the function without the underscore return new tensor

In [17]:
res_y.add(1)                                     # return a new tensor

tensor([[2.3190, 2.7024, 2.7576, 2.4048, 2.8386],
        [2.3427, 2.7705, 2.4187, 2.7239, 2.3240],
        [2.1501, 2.5568, 2.8509, 2.4983, 2.4110],
        [2.2643, 2.4154, 2.3221, 2.3416, 2.2059]])

In [18]:
res_y                                           # unchanged tensor

tensor([[1.3190, 1.7024, 1.7576, 1.4048, 1.8386],
        [1.3427, 1.7705, 1.4187, 1.7239, 1.3240],
        [1.1501, 1.5568, 1.8509, 1.4983, 1.4110],
        [1.2643, 1.4154, 1.3221, 1.3416, 1.2059]])

In [19]:
res_y.add_(1)                                   # change the tensor inplace

tensor([[2.3190, 2.7024, 2.7576, 2.4048, 2.8386],
        [2.3427, 2.7705, 2.4187, 2.7239, 2.3240],
        [2.1501, 2.5568, 2.8509, 2.4983, 2.4110],
        [2.2643, 2.4154, 2.3221, 2.3416, 2.2059]])

In [20]:
res_y                                          # changed tensor

tensor([[2.3190, 2.7024, 2.7576, 2.4048, 2.8386],
        [2.3427, 2.7705, 2.4187, 2.7239, 2.3240],
        [2.1501, 2.5568, 2.8509, 2.4983, 2.4110],
        [2.2643, 2.4154, 2.3221, 2.3416, 2.2059]])

## Reshaping or Resizing a Tensor

In [21]:
new_row_dim = 5
new_col_dim = 4

In [22]:
res_y.reshape(new_row_dim, new_col_dim)            # return a new tensor after resize/reshape

tensor([[2.3190, 2.7024, 2.7576, 2.4048],
        [2.8386, 2.3427, 2.7705, 2.4187],
        [2.7239, 2.3240, 2.1501, 2.5568],
        [2.8509, 2.4983, 2.4110, 2.2643],
        [2.4154, 2.3221, 2.3416, 2.2059]])

In [23]:
res_y                                             # original tensor is unchanged

tensor([[2.3190, 2.7024, 2.7576, 2.4048, 2.8386],
        [2.3427, 2.7705, 2.4187, 2.7239, 2.3240],
        [2.1501, 2.5568, 2.8509, 2.4983, 2.4110],
        [2.2643, 2.4154, 2.3221, 2.3416, 2.2059]])

In [24]:
res_y.resize_(new_row_dim, new_col_dim)           # change original tensor inpace

tensor([[2.3190, 2.7024, 2.7576, 2.4048],
        [2.8386, 2.3427, 2.7705, 2.4187],
        [2.7239, 2.3240, 2.1501, 2.5568],
        [2.8509, 2.4983, 2.4110, 2.2643],
        [2.4154, 2.3221, 2.3416, 2.2059]])

In [25]:
res_y                                             # changed original tensor

tensor([[2.3190, 2.7024, 2.7576, 2.4048],
        [2.8386, 2.3427, 2.7705, 2.4187],
        [2.7239, 2.3240, 2.1501, 2.5568],
        [2.8509, 2.4983, 2.4110, 2.2643],
        [2.4154, 2.3221, 2.3416, 2.2059]])

## Array -> Tensor [vice-versa]

In [26]:
res_x_tensor = torch.from_numpy(res_x)
res_x_tensor

tensor([[1.8846, 1.9627, 1.4885, 1.5686, 1.8538],
        [1.9760, 1.2935, 1.2867, 1.3266, 1.6527],
        [1.5830, 1.9386, 1.8977, 1.6125, 1.7133],
        [1.6760, 1.9032, 1.5446, 1.9180, 1.9330]], dtype=torch.float64)

In [27]:
res_y_array = res_y.numpy()
res_y_array

array([[2.3190475, 2.7023697, 2.7575743, 2.4048216],
       [2.8385577, 2.3427489, 2.7705302, 2.4186542],
       [2.7238803, 2.3240047, 2.1501138, 2.5567734],
       [2.8508897, 2.498326 , 2.4109871, 2.2643135],
       [2.4154303, 2.3220742, 2.3415706, 2.2059016]], dtype=float32)

## Caveat

pytorch tensor from numpy array (or other way) they share same memory location, so mutation in one make other one mutated.

In [28]:
a = np.ones([5,5])
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
b = torch.from_numpy(a)
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [30]:
a[2][3] = 1000

In [31]:
a

array([[   1.,    1.,    1.,    1.,    1.],
       [   1.,    1.,    1.,    1.,    1.],
       [   1.,    1.,    1., 1000.,    1.],
       [   1.,    1.,    1.,    1.,    1.],
       [   1.,    1.,    1.,    1.,    1.]])

In [32]:
b

tensor([[   1.,    1.,    1.,    1.,    1.],
        [   1.,    1.,    1.,    1.,    1.],
        [   1.,    1.,    1., 1000.,    1.],
        [   1.,    1.,    1.,    1.,    1.],
        [   1.,    1.,    1.,    1.,    1.]], dtype=torch.float64)