# Pytorch

- __`torch`__: a Tensor library like NumPy, with strong GPU support
- __`torch.autograd`__: a tape based automatic differentiation library that supports all differentiable Tensor operations in torch
- __`torch.nn`__: a neural networks library deeply integrated with autograd designed for maximum flexibility
- __`torch.optim`__: an optimization package to be used with torch.nn with standard optimization methods such as SGD, RMSProp, LBFGS, Adam etc.
- __`torch.multiprocessing`__: python multiprocessing, but with magical memory sharing of torch Tensors across processes. Useful for data loading and hogwild training.
- __`torch.utils`__: DataLoader, Trainer and other utility functions for convenience
- __`torch.legacy`(.nn/.optim)__: legacy code that has been ported over from torch for backward compatibility reasons


In [1]:
import numpy as np
import torch

## Similarity of numpy array and pytorch tensor

### numpy

In [2]:
row_dim = 4
col_dim = 5

In [3]:
x = np.random.rand(row_dim, col_dim)

In [4]:
print(type(x))
print(f'Shape of x: {x.shape}\n')
print(f'x: \n{x}')

<class 'numpy.ndarray'>
Shape of x: (4, 5)

x: 
[[0.40251969 0.01048708 0.38562073 0.54968105 0.43163407]
 [0.21678273 0.51899483 0.29273886 0.28672503 0.70498801]
 [0.24473728 0.67390052 0.12382299 0.34588224 0.0736415 ]
 [0.4669683  0.01719792 0.55787204 0.23925945 0.46101518]]


In [5]:
ones_x = np.ones(x.shape)

print(f'ones_x: \n{ones_x}')

ones_x: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
res_x = x + ones_x

print(f'res_x: \n{res_x}')

res_x: 
[[1.40251969 1.01048708 1.38562073 1.54968105 1.43163407]
 [1.21678273 1.51899483 1.29273886 1.28672503 1.70498801]
 [1.24473728 1.67390052 1.12382299 1.34588224 1.0736415 ]
 [1.4669683  1.01719792 1.55787204 1.23925945 1.46101518]]


In [7]:
res_x[0]

array([1.40251969, 1.01048708, 1.38562073, 1.54968105, 1.43163407])

In [8]:
res_x[:, 2:4]

array([[1.38562073, 1.54968105],
       [1.29273886, 1.28672503],
       [1.12382299, 1.34588224],
       [1.55787204, 1.23925945]])

In [9]:
res_x[1:3, :]

array([[1.21678273, 1.51899483, 1.29273886, 1.28672503, 1.70498801],
       [1.24473728, 1.67390052, 1.12382299, 1.34588224, 1.0736415 ]])

### pytorch

In [10]:
y = torch.rand(row_dim, col_dim)

In [11]:
print(type(y))
print(f'Shape of y: {y.shape}\n')
print(f'y: \n{y}')

<class 'torch.Tensor'>
Shape of y: torch.Size([4, 5])

y: 
tensor([[0.2439, 0.6108, 0.9166, 0.6872, 0.0903],
        [0.1324, 0.4699, 0.7792, 0.2792, 0.2369],
        [0.6820, 0.9757, 0.1131, 0.2465, 0.9557],
        [0.6996, 0.7817, 0.7439, 0.0369, 0.6367]])


In [12]:
ones_y = torch.ones(y.shape)

print(f'ones_y: \n{ones_y}')

ones_y: 
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [13]:
res_y = y + ones_y

print(f'res_y: \n{res_y}')

res_y: 
tensor([[1.2439, 1.6108, 1.9166, 1.6872, 1.0903],
        [1.1324, 1.4699, 1.7792, 1.2792, 1.2369],
        [1.6820, 1.9757, 1.1131, 1.2465, 1.9557],
        [1.6996, 1.7817, 1.7439, 1.0369, 1.6367]])


In [14]:
res_y[0]

tensor([1.2439, 1.6108, 1.9166, 1.6872, 1.0903])

In [15]:
res_y[:, 2:4]

tensor([[1.9166, 1.6872],
        [1.7792, 1.2792],
        [1.1131, 1.2465],
        [1.7439, 1.0369]])

In [16]:
res_y[1:3, :]

tensor([[1.1324, 1.4699, 1.7792, 1.2792, 1.2369],
        [1.6820, 1.9757, 1.1131, 1.2465, 1.9557]])

## Special Function

In Pytorch almost every operation over tensor may change the tensor inpalce or return anew tensor. 
- the function with under-score after its name change the tensor inplace
- the function without the underscore return new tensor

In [17]:
res_y.add(1)                                     # return a new tensor

tensor([[2.2439, 2.6108, 2.9166, 2.6872, 2.0903],
        [2.1324, 2.4699, 2.7792, 2.2792, 2.2369],
        [2.6820, 2.9757, 2.1131, 2.2465, 2.9557],
        [2.6996, 2.7817, 2.7439, 2.0369, 2.6367]])

In [18]:
res_y                                           # unchanged tensor

tensor([[1.2439, 1.6108, 1.9166, 1.6872, 1.0903],
        [1.1324, 1.4699, 1.7792, 1.2792, 1.2369],
        [1.6820, 1.9757, 1.1131, 1.2465, 1.9557],
        [1.6996, 1.7817, 1.7439, 1.0369, 1.6367]])

In [19]:
res_y.add_(1)                                   # change the tensor inplace

tensor([[2.2439, 2.6108, 2.9166, 2.6872, 2.0903],
        [2.1324, 2.4699, 2.7792, 2.2792, 2.2369],
        [2.6820, 2.9757, 2.1131, 2.2465, 2.9557],
        [2.6996, 2.7817, 2.7439, 2.0369, 2.6367]])

In [20]:
res_y                                          # changed tensor

tensor([[2.2439, 2.6108, 2.9166, 2.6872, 2.0903],
        [2.1324, 2.4699, 2.7792, 2.2792, 2.2369],
        [2.6820, 2.9757, 2.1131, 2.2465, 2.9557],
        [2.6996, 2.7817, 2.7439, 2.0369, 2.6367]])

## Reshaping or Resizing a Tensor

In [21]:
new_row_dim = 5
new_col_dim = 4

In [22]:
res_y.reshape(new_row_dim, new_col_dim)            # return a new tensor after resize/reshape

tensor([[2.2439, 2.6108, 2.9166, 2.6872],
        [2.0903, 2.1324, 2.4699, 2.7792],
        [2.2792, 2.2369, 2.6820, 2.9757],
        [2.1131, 2.2465, 2.9557, 2.6996],
        [2.7817, 2.7439, 2.0369, 2.6367]])

In [23]:
res_y                                             # original tensor is unchanged

tensor([[2.2439, 2.6108, 2.9166, 2.6872, 2.0903],
        [2.1324, 2.4699, 2.7792, 2.2792, 2.2369],
        [2.6820, 2.9757, 2.1131, 2.2465, 2.9557],
        [2.6996, 2.7817, 2.7439, 2.0369, 2.6367]])

In [24]:
res_y.resize_(new_row_dim, new_col_dim)           # change original tensor inpace

tensor([[2.2439, 2.6108, 2.9166, 2.6872],
        [2.0903, 2.1324, 2.4699, 2.7792],
        [2.2792, 2.2369, 2.6820, 2.9757],
        [2.1131, 2.2465, 2.9557, 2.6996],
        [2.7817, 2.7439, 2.0369, 2.6367]])

In [25]:
res_y                                             # changed original tensor

tensor([[2.2439, 2.6108, 2.9166, 2.6872],
        [2.0903, 2.1324, 2.4699, 2.7792],
        [2.2792, 2.2369, 2.6820, 2.9757],
        [2.1131, 2.2465, 2.9557, 2.6996],
        [2.7817, 2.7439, 2.0369, 2.6367]])